/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DevTimer;
import java.io.*;
import java.util.*;

/**
 *
 * @author jym
 */
public class DefaultOptions extends javax.swing.JFrame {
    
    int preWash;
    int developer;
    int stopBath;
    int fixer;
    int hypoClearing;
    int finalWash;
    int wettingAgent;
    int initialAgitation;
    int thenAgitation;

  
    /**
     * Creates new form DefaultOptions
     */
    public DefaultOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DefaultOptionsPanel = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        lblPreWash = new javax.swing.JLabel();
        preWashMin = new javax.swing.JComboBox();
        preWashColon = new javax.swing.JLabel();
        preWashSec = new javax.swing.JComboBox();
        lblStopBath = new javax.swing.JLabel();
        developerMin = new javax.swing.JComboBox();
        developerSec = new javax.swing.JComboBox();
        stopBathMin = new javax.swing.JComboBox();
        stopBathSec = new javax.swing.JComboBox();
        fixerMin = new javax.swing.JComboBox();
        fixerSec = new javax.swing.JComboBox();
        hypoClearingMin = new javax.swing.JComboBox();
        hypoClearingSec = new javax.swing.JComboBox();
        lblFixer = new javax.swing.JLabel();
        lblHypoClearing = new javax.swing.JLabel();
        lblFinalWash = new javax.swing.JLabel();
        finalWashColon = new javax.swing.JLabel();
        hypoClearingColon = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        fixerColon = new javax.swing.JLabel();
        stopBathColon = new javax.swing.JLabel();
        finalWashSec = new javax.swing.JComboBox();
        wettingAgentColon = new javax.swing.JLabel();
        finalWashMin = new javax.swing.JComboBox();
        lblWettingAgent = new javax.swing.JLabel();
        lblSaved = new javax.swing.JLabel();
        wettingAgentSec = new javax.swing.JComboBox();
        wettingAgentColon1 = new javax.swing.JLabel();
        wettingAgentMin = new javax.swing.JComboBox();
        lblWettingAgent1 = new javax.swing.JLabel();
        lblAgitation = new javax.swing.JLabel();
        lblThen = new javax.swing.JLabel();
        initialAgitationSec = new javax.swing.JComboBox();
        initialAgitationColon = new javax.swing.JLabel();
        initialAgitationMin = new javax.swing.JComboBox();
        thenSec = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Dev Timer - Default Options");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        DefaultOptionsPanel.setBackground(new java.awt.Color(1, 1, 1));

        lblHeader.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(225, 225, 225));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Default options");
        lblHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblPreWash.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblPreWash.setForeground(new java.awt.Color(225, 225, 225));
        lblPreWash.setText("Pre wash");

        preWashMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        preWashMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        preWashColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        preWashColon.setForeground(new java.awt.Color(225, 225, 225));
        preWashColon.setText(":");

        preWashSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        preWashSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        lblStopBath.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblStopBath.setForeground(new java.awt.Color(225, 225, 225));
        lblStopBath.setText("Developer");

        developerMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        developerMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        developerSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        developerSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        stopBathMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        stopBathMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        stopBathSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        stopBathSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        fixerMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        fixerMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        fixerSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        fixerSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        hypoClearingMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        hypoClearingMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        hypoClearingSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        hypoClearingSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        lblFixer.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblFixer.setForeground(new java.awt.Color(225, 225, 225));
        lblFixer.setText("Stop bath");

        lblHypoClearing.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblHypoClearing.setForeground(new java.awt.Color(225, 225, 225));
        lblHypoClearing.setText("Fixer");

        lblFinalWash.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblFinalWash.setForeground(new java.awt.Color(225, 225, 225));
        lblFinalWash.setText("Hypo clearing");

        finalWashColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        finalWashColon.setForeground(new java.awt.Color(225, 225, 225));
        finalWashColon.setText(":");

        hypoClearingColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        hypoClearingColon.setForeground(new java.awt.Color(225, 225, 225));
        hypoClearingColon.setText(":");

        btnSave.setBackground(new java.awt.Color(1, 1, 1));
        btnSave.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(225, 225, 225));
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.MatteBorder(null));
        btnSave.setBorderPainted(false);
        btnSave.setMaximumSize(new java.awt.Dimension(150, 40));
        btnSave.setMinimumSize(new java.awt.Dimension(150, 40));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        fixerColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        fixerColon.setForeground(new java.awt.Color(225, 225, 225));
        fixerColon.setText(":");

        stopBathColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        stopBathColon.setForeground(new java.awt.Color(225, 225, 225));
        stopBathColon.setText(":");

        finalWashSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        finalWashSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        wettingAgentColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        wettingAgentColon.setForeground(new java.awt.Color(225, 225, 225));
        wettingAgentColon.setText(":");

        finalWashMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        finalWashMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        lblWettingAgent.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblWettingAgent.setForeground(new java.awt.Color(225, 225, 225));
        lblWettingAgent.setText("Final wash");

        lblSaved.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblSaved.setForeground(new java.awt.Color(225, 225, 225));

        wettingAgentSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        wettingAgentSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        wettingAgentColon1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        wettingAgentColon1.setForeground(new java.awt.Color(225, 225, 225));
        wettingAgentColon1.setText(":");

        wettingAgentMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        wettingAgentMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        lblWettingAgent1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblWettingAgent1.setForeground(new java.awt.Color(225, 225, 225));
        lblWettingAgent1.setText("Wetting agent");

        lblAgitation.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblAgitation.setForeground(new java.awt.Color(226, 226, 226));
        lblAgitation.setText("Initial agitation");

        lblThen.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        lblThen.setForeground(new java.awt.Color(225, 225, 225));
        lblThen.setText("then");

        initialAgitationSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        initialAgitationSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        initialAgitationColon.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        initialAgitationColon.setForeground(new java.awt.Color(225, 225, 225));
        initialAgitationColon.setText(":");

        initialAgitationMin.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        initialAgitationMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        thenSec.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        thenSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 226, 226));
        jLabel1.setText("seconds/minute");

        javax.swing.GroupLayout DefaultOptionsPanelLayout = new javax.swing.GroupLayout(DefaultOptionsPanel);
        DefaultOptionsPanel.setLayout(DefaultOptionsPanelLayout);
        DefaultOptionsPanelLayout.setHorizontalGroup(
            DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefaultOptionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSaved, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefaultOptionsPanelLayout.createSequentialGroup()
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                        .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(lblPreWash))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefaultOptionsPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFinalWash, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHypoClearing, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFixer, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblStopBath, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hypoClearingMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stopBathMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(developerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(preWashMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hypoClearingColon)
                            .addComponent(finalWashColon)
                            .addComponent(fixerColon)
                            .addComponent(stopBathColon)
                            .addComponent(preWashColon))
                        .addGap(4, 4, 4)
                        .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(preWashSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hypoClearingSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fixerSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stopBathSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(developerSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                                .addComponent(lblWettingAgent1)
                                .addGap(18, 18, 18)
                                .addComponent(wettingAgentMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(wettingAgentColon1)
                                .addGap(4, 4, 4)
                                .addComponent(wettingAgentSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                                .addComponent(lblWettingAgent)
                                .addGap(18, 18, 18)
                                .addComponent(finalWashMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(wettingAgentColon)
                                .addGap(4, 4, 4)
                                .addComponent(finalWashSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                        .addComponent(lblAgitation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(initialAgitationMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(initialAgitationColon)
                        .addGap(4, 4, 4)
                        .addComponent(initialAgitationSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                        .addComponent(lblThen)
                        .addGap(18, 18, 18)
                        .addComponent(thenSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(93, 93, 93))
        );
        DefaultOptionsPanelLayout.setVerticalGroup(
            DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefaultOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preWashMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preWashSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPreWash)
                    .addComponent(preWashColon)
                    .addComponent(lblAgitation)
                    .addComponent(initialAgitationMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialAgitationSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(initialAgitationColon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(developerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(developerSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopBathColon)
                    .addComponent(lblStopBath)
                    .addComponent(lblThen)
                    .addComponent(thenSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopBathMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stopBathSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFixer)
                    .addComponent(fixerColon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fixerSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypoClearingColon)
                    .addComponent(lblHypoClearing))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hypoClearingMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hypoClearingSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinalWash)
                    .addComponent(finalWashColon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalWashMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalWashSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWettingAgent)
                    .addComponent(wettingAgentColon))
                .addGap(14, 14, 14)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wettingAgentMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wettingAgentSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblWettingAgent1)
                    .addComponent(wettingAgentColon1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(DefaultOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaved, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DefaultOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DefaultOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Work out the pre wash time in seconds
        preWash = preWashMin.getSelectedIndex();
        preWash = preWash * 60 + preWashSec.getSelectedIndex();
        // Work out the developer time in seconds
        developer = developerMin.getSelectedIndex();
        developer = developer * 60 + developerSec.getSelectedIndex();
        // Work out the stop bath time in seconds
        stopBath = stopBathMin.getSelectedIndex();
        stopBath = stopBath * 60 + stopBathSec.getSelectedIndex();
        // Work out the fixer time in seconds
        fixer = fixerMin.getSelectedIndex();
        fixer = fixer * 60 + fixerSec.getSelectedIndex();
        // Work out the hypo clearing time in seconds
        hypoClearing = hypoClearingMin.getSelectedIndex();
        hypoClearing = hypoClearing * 60 + hypoClearingSec.getSelectedIndex();
        // Work out the final wash time in seconds
        finalWash = finalWashMin.getSelectedIndex();
        finalWash = finalWash * 60 + finalWashSec.getSelectedIndex();
        // Work out the wetting agent time in seconds
        wettingAgent = wettingAgentMin.getSelectedIndex();
        wettingAgent = wettingAgent * 60 + wettingAgentSec.getSelectedIndex();
        // Work out the initial agitation time in seconds
        initialAgitation = initialAgitationMin.getSelectedIndex();
        initialAgitation = initialAgitation * 60 + initialAgitationSec.getSelectedIndex();
        // Work out the intermitent agitation time (seconds/minute)
        thenAgitation = thenSec.getSelectedIndex();
        
        try {
        BufferedWriter out = new BufferedWriter(new FileWriter("usersettings.csv"));
            out.write(preWash + "\n");
            out.write(developer + "\n");
            out.write(stopBath + "\n");
            out.write(fixer + "\n");
            out.write(hypoClearing + "\n");
            out.write(finalWash + "\n");
            out.write(wettingAgent + "\n");
            out.write(initialAgitation + "\n");
            out.write(thenAgitation + "\n");
            out.close();
            lblSaved.setText("Settings saved");
            System.out.println("\n****** Settings overwritten ******");
        } catch (IOException e) {
            lblSaved.setText("Error");
            System.out.println("\n****** Error saving settings ******");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefaultOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefaultOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefaultOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefaultOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DefaultOptions().setVisible(true);
            }
        });
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DefaultOptionsPanel;
    private javax.swing.JButton btnSave;
    public static javax.swing.JComboBox developerMin;
    public static javax.swing.JComboBox developerSec;
    private javax.swing.JLabel finalWashColon;
    public static javax.swing.JComboBox finalWashMin;
    public static javax.swing.JComboBox finalWashSec;
    private javax.swing.JLabel fixerColon;
    public static javax.swing.JComboBox fixerMin;
    public static javax.swing.JComboBox fixerSec;
    private javax.swing.JLabel hypoClearingColon;
    public static javax.swing.JComboBox hypoClearingMin;
    public static javax.swing.JComboBox hypoClearingSec;
    private javax.swing.JLabel initialAgitationColon;
    public static javax.swing.JComboBox initialAgitationMin;
    public static javax.swing.JComboBox initialAgitationSec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAgitation;
    private javax.swing.JLabel lblFinalWash;
    private javax.swing.JLabel lblFixer;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHypoClearing;
    private javax.swing.JLabel lblPreWash;
    private javax.swing.JLabel lblSaved;
    private javax.swing.JLabel lblStopBath;
    private javax.swing.JLabel lblThen;
    private javax.swing.JLabel lblWettingAgent;
    private javax.swing.JLabel lblWettingAgent1;
    private javax.swing.JLabel preWashColon;
    public static javax.swing.JComboBox preWashMin;
    public static javax.swing.JComboBox preWashSec;
    private javax.swing.JLabel stopBathColon;
    public static javax.swing.JComboBox stopBathMin;
    public static javax.swing.JComboBox stopBathSec;
    public static javax.swing.JComboBox thenSec;
    private javax.swing.JLabel wettingAgentColon;
    private javax.swing.JLabel wettingAgentColon1;
    public static javax.swing.JComboBox wettingAgentMin;
    public static javax.swing.JComboBox wettingAgentSec;
    // End of variables declaration//GEN-END:variables
}
